hide_window_decorations titlebar-only
draw_minimal_borders yes
macos_option_as_alt left

# Font
font_family      JetBrainsMono Nerd Font
font_size        12.5

# Window
window_border_width 1
confirm_os_window_close 0

# Transparency
background_opacity 0.88
background_blur 32

# Allow live opacity adjustment
dynamic_background_opacity yes

# Tabs
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

# Theme gets included separately
include Tokyo-Night.conf


